apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: ecoearn-dev

namePrefix: dev-

replicas:
- name: ecoearn-app
  count: 1

images:
- name: ecoearn
  newTag: dev-latest

patches:
- path: deployment-patch.yaml

labels:
- pairs:
    environment: development
  includeSelectors: false