apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: ecoearn-dev

namePrefix: dev-

images:
- name: ecoearn
  newTag: dev-latest

patches:
- path: deployment-patch.yaml