apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: ecoearn

replicas:
- name: ecoearn-app
  count: 3

images:
- name: ecoearn
  newTag: v1.0.0

patches:
- path: deployment-patch.yaml

labels:
- pairs:
    environment: production
  includeSelectors: false