apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: ecoearn

images:
- name: ecoearn
  newTag: v1.0.0

patchesStrategicMerge:
- deployment-patch.yaml
- pairs:
    environment: production
  includeSelectors: false